#:schema node_modules/wrangler/config-schema.json
name = "promptexecution-comic-cron"
main = "functions/_worker.js"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 9 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "llm-comic-db"
database_id = "63d24854-1c1d-4f86-8029-242c298177a9"

[[r2_buckets]]
binding = "COMICS_BUCKET"
bucket_name = "llm-comics"

[env.production.ai]
binding = "AI"

[[env.production.d1_databases]]
binding = "DB"
database_name = "llm-comic-db"
database_id = "63d24854-1c1d-4f86-8029-242c298177a9"

[[env.production.r2_buckets]]
binding = "COMICS_BUCKET"
bucket_name = "llm-comics"

[env.production.vars]
SCRIPT_MODEL_A = "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"
SCRIPT_MODEL_B = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
TOPIC_MODEL = "@cf/qwen/qwen3-30b-a3b-fp8"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
