#:schema node_modules/wrangler/config-schema.json
name = "promptexecution-comic-cron"
main = "functions/_worker.js"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 9 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "llm-comic-db"
database_id = "63d24854-1c1d-4f86-8029-242c298177a9"

[[r2_buckets]]
binding = "COMICS_BUCKET"
bucket_name = "llm-comics"

[env.production.ai]
binding = "AI"

[env.production.vars]
IMAGE_MODEL_A = "@cf/bytedance/stable-diffusion-xl-lightning"
IMAGE_MODEL_B = "@cf/black-forest-labs/flux-1-schnell"
TOPIC_MODEL = "@cf/meta/llama-3.1-8b-instruct"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
